### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by trunet** [spark/particle-dev#154]
Brand new ATOM(never had it installed before), just installed particle-dev-complete and I'm receiving this error:

```
> serialport@2.0.6 install /tmp/apm-install-dir-116711-22741-s4iavd/node_modules/particle-dev/node_modules/serialport
> node-pre-gyp install --fallback-to-build --runtime=atom-shell

make: Entering directory '/tmp/apm-install-dir-116711-22741-s4iavd/node_modules/particle-dev/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
serialport.target.mk:90: recipe for target 'Release/obj.target/serialport/src/serialport.o' failed
make: Leaving directory '/tmp/apm-install-dir-116711-22741-s4iavd/node_modules/particle-dev/node_modules/serialport/build'
Failed to execute 'node-gyp build --fallback-to-build --runtime=atom-shell --module=/tmp/apm-install-dir-116711-22741-s4iavd/node_modules/particle-dev/node_modules/serialport/build/Release/electron-v0.37-linux-x64/serialport.node --module_name=serialport --module_path=/tmp/apm-install-dir-116711-22741-s4iavd/node_modules/particle-dev/node_modules/serialport/build/Release/electron-v0.37-linux-x64' (1)

npm WARN deprecated spark@0.5.10: Use particle-api-js instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN installMany node-pre-gyp was bundled with serialport@2.0.6, but bundled package wasn't found in unpacked tree
npm WARN installMany node-pre-gyp-github was bundled with serialport@2.0.6, but bundled package wasn't found in unpacked tree
npm WARN installMany nopt was bundled with node-pre-gyp@0.6.17, but bundled package wasn't found in unpacked tree
npm WARN installMany npmlog was bundled with node-pre-gyp@0.6.17, but bundled package wasn't found in unpacked tree
npm WARN installMany request was bundled with node-pre-gyp@0.6.17, but bundled package wasn't found in unpacked tree
npm WARN installMany semver was bundled with node-pre-gyp@0.6.17, but bundled package wasn't found in unpacked tree
npm WARN installMany tar was bundled with node-pre-gyp@0.6.17, but bundled package wasn't found in unpacked tree
npm WARN installMany tar-pack was bundled with node-pre-gyp@0.6.17, but bundled package wasn't found in unpacked tree
npm WARN installMany mkdirp was bundled with node-pre-gyp@0.6.17, but bundled package wasn't found in unpacked tree
npm WARN installMany rc was bundled with node-pre-gyp@0.6.17, but bundled package wasn't found in unpacked tree
npm WARN installMany rimraf was bundled with node-pre-gyp@0.6.17, but bundled package wasn't found in unpacked tree
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
In file included from ../src/serialport.h:5:0,
                 from ../src/serialport.cpp:3:
../node_modules/nan/nan.h:590:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../node_modules/nan/nan.h:590:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^
../node_modules/nan/nan.h:591:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:596:20: error: variable or field ‘RemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../node_modules/nan/nan.h:596:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../node_modules/nan/nan.h:601:20: error: variable or field ‘AddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../node_modules/nan/nan.h:601:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^
../node_modules/nan/nan.h:602:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../node_modules/nan/nan.h:607:20: error: variable or field ‘RemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../node_modules/nan/nan.h:607:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^
make: *** [Release/obj.target/serialport/src/serialport.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.4.0-34-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--runtime=atom-shell" "--module=/tmp/apm-install-dir-116711-22741-s4iavd/node_modules/particle-dev/node_modules/serialport/build/Release/electron-v0.37-linux-x64/serialport.node" "--module_name=serialport" "--module_path=/tmp/apm-install-dir-116711-22741-s4iavd/node_modules/particle-dev/node_modules/serialport/build/Release/electron-v0.37-linux-x64"
gyp ERR! cwd /tmp/apm-install-dir-116711-22741-s4iavd/node_modules/particle-dev/node_modules/serialport
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --runtime=atom-shell --module=/tmp/apm-install-dir-116711-22741-s4iavd/node_modules/particle-dev/node_modules/serialport/build/Release/electron-v0.37-linux-x64/serialport.node --module_name=serialport --module_path=/tmp/apm-install-dir-116711-22741-s4iavd/node_modules/particle-dev/node_modules/serialport/build/Release/electron-v0.37-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/apm-install-dir-116711-22741-s4iavd/node_modules/particle-dev/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 4.4.0-34-generic
node-pre-gyp ERR! command "node" "/tmp/apm-install-dir-116711-22741-s4iavd/node_modules/particle-dev/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--runtime=atom-shell"
node-pre-gyp ERR! cwd /tmp/apm-install-dir-116711-22741-s4iavd/node_modules/particle-dev/node_modules/serialport
node-pre-gyp ERR! node -v v0.10.40
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok 
npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/wsartori/.atom/.apm/.apmrc" "--userconfig" "/home/wsartori/.atom/.apmrc" "install" "/tmp/d-116711-22741-wly7m4/package.tgz" "--target=0.37.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! serialport@2.0.6 install: `node-pre-gyp install --fallback-to-build --runtime=atom-shell`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@2.0.6 install script 'node-pre-gyp install --fallback-to-build --runtime=atom-shell'.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --runtime=atom-shell
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116711-22741-s4iavd/npm-debug.log
```

**Comment by trunet** [comment]
Same as #152 closing... Sorry!
